### ISSUE TITLE
Incorrect result for integer division

### ISSUE THREAD

**Issue by kromych** [li-script/lightning#7] opened 2022-07-04 16:49 UTC
![image](https://user-images.githubusercontent.com/745493/177194542-bff46fc6-d858-4284-bfc8-ec2224bcc7d3.png)

**Comment by can1357** [comment] 2022-07-04 17:32
You can't really represent that value in a double which is type for all numbers in current version of master. WIP version will include parser time errors for cases such as this but closing the issue for now since this is expected behavior with a floating point number either way.

**Closed as completed by can1357** 2022-07-04 17:32 UTC
